### PR TITLE
Allow Symfony 7

### PR DESCRIPTION
**Pull request by Jean85**
Same as #17

### CODE REVIEW

**Comment by Jean85** [comment]
#19 solved most of the CI issues, but now I discovered that I need to allow Symfony 7 in `facile-it/symfony-functional-testcase`!

**Comment by Jean85** [comment]
@starred-gijs are you able to test this PR in your project(s)?

**Comment by Jean85** [comment]
Reviewing the diff, there's no significant difference to grant more testing, I'll proceed with a new minor tag.

**Comment by starred-gijs** [comment]
Sorry I was not able to test this yesterday. Thanks for your work, very much appreciated!

**Pull request merged**
